# https://github.com/bbatsov/rubocop#includingexcluding-files
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'script/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/schemas/*'
    - 'db/seeds/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'

  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2

Rails:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'Guardfile'
    - 'app/decorators/**/*'
    - 'app/views/**/*'
    - 'app/models/concerns/**/*'
    - 'app/controllers/concerns/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'Guardfile'
    - 'app/decorators/**/*'
    - 'app/views/**/*'
    - 'app/models/concerns/**/*'
    - 'app/controllers/concerns/**/*'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
  MinDigits: 5

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses
