version: '2'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - "./server:/root/app"
    volumes_from:
      - datastore
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - SECRET_KEY_BASE=slfjlakwsjlfajsljlkf
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  datastore:
    image: "busybox"
    volumes:
      - "server:/usr/local/bundle"
      - "db:/var/lib/mysql"

volumes:
  db:
    driver: local
  server:
    driver: local
