version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          DATABASE_USER: frimania
      - image: circleci/postgres:10.4-alpine-ram
        environment:
          POSTGRES_USER: frimania
          POSTGRES_DB: frimania_test
    steps:
      - checkout

      - restore_cache:
          key: cache-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path .bundle
      - save_cache:
          key: cache-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

      - run: bundle exec rubocop
      - run: bundle exec rspec
